# Available hotkeys:
# a-z, 0-9, f1-f12 and any other symbols
# enter, space, backspace, delete, escape, tab and shift+tab
# shift+<a-z>
# ctrl+<a-z>

hotkeys:
  help: f1
  up: k
  quickUp: shift+k
  veryQuickUp: ctrl+k
  switchFilterMode: ctrl+k
  down: j
  quickDown: shift+j
  veryQuickDown: ctrl+j
  backSwitchFilterMode: ctrl+j
  left: h
  right: l
  switchWindow: tab
  backSwitchWindows: shift+tab
  loadJournal: enter
  goToFilter: /
  goToEnd: ctrl+e
  goToTop: ctrl+a
  tailModeMore: ctrl+x
  tailModeLess: ctrl+z
  updateIntervalMore: ctrl+p
  updateIntervalLess: ctrl+o
  autoUpdateJournal: ctrl+u
  updateJournal: ctrl+r
  updateLists: ctrl+q
  colorDisable: ctrl+w
  tailspinEnable: ctrl+n
  switchDockerMode: ctrl+d
  switchStreamMode: ctrl+s
  timestampShow: ctrl+t
  exit: ctrl+c

# Default flag values (lower priority)

settings:
  customPath: /opt
  tailMode: 50000
  updateInterval: 5
  disableAutoUpdate: false
  disableColor: false
  disableMouse: false
  disableTimestamp: false
  onlyStream: false
  disableFastMode: false

# Available colors:
# default, green, black, yellow, red, blue, cyan, magenta, white

interface:
  foregroundColor: default
  backgroundColor: default
  selectedForegroundColor: black
  selectedBackgroundColor: green
  frameColor: default
  titleColor: default
  selectedFrameColor: green
  selectedTitleColor: green
  statusColor: yellow
  errorColor: red