# Default flag values (lower priority)
settings:
  tailModeDisable: false
  tailModeLines: 10000
  updateInterval: 5
  minSymbolFilter: 3
  mouseDisable: false
  wrapModeDisable: false
  dockerStreamOnly: false
  dockerContext: default
  podmanContext: ""
  kubernetesContext: default
  kubernetesNamespace: all
  customPath: /opt
  colorMode: default
  colorActionsDisable: false
  sinceDateFilterMode: false
  untilDateFilterMode: false
  disableFastMode: false

# Available hotkeys:
# a-z, shift+<a-z>, ctrl+<a-z>, 0-9, f1-f12 and any other symbols
# tab, shift+tab, enter, space, backspace, del/delete and esc/escape
hotkeys:
  showHelp: f1
  showManager: f2
  switchWindow: tab
  backSwitchWindows: shift+tab
  up: k
  quickUp: shift+k
  veryQuickUp: ctrl+k
  switchFilterMode: ctrl+k
  down: j
  quickDown: shift+j
  veryQuickDown: ctrl+j
  backSwitchFilterMode: ctrl+j
  left: h
  right: l
  disableFilterByDate: delete
  loadJournal: enter
  goToFilter: /
  goToEnd: ctrl+e
  goToTop: ctrl+a
  tailModeMore: "]"
  tailModeLess: "["
  updateIntervalMore: "}"
  updateIntervalLess: "{"
  autoUpdateJournal: ctrl+u
  updateJournal: ctrl+r
  updateLists: ctrl+q
  switchColorMode: ctrl+w
  switchPriority: ctrl+p
  switchDockerMode: ctrl+d
  switchStreamMode: ctrl+s
  timestampShow: ctrl+t
  exit: ctrl+c

# Default interface settings
interface:
  # Lists in panels loaded when the interface starts
  # Available system log lists: services, systemUnits, userUnits, kernelBoot, auditd
  systemLogList: services
  # Available file log lists: varlog, customPath, home, descriptor
  fileLogList: varlog
  # Available container log lists: docker, compose, podman, kubernetes
  containerLogList: docker
  # Available colors: default, green, black, yellow, red, blue, cyan, magenta, white
  foregroundColor: default
  backgroundColor: default
  selectedForegroundColor: black
  selectedBackgroundColor: green
  frameColor: default
  titleColor: default
  selectedFrameColor: green
  selectedTitleColor: green
  errorColor: red

# List of ssh hosts with flags for connection from the interface
# ssh:
#   hosts:
#     - lifailon@192.168.3.101
#     - lifailon@192.168.3.105 -p 2121 -o Compression=yes
#     - lifailon@192.168.3.106 -o StrictHostKeyChecking=no -o ConnectTimeout=5