# Default flag values (lower priority)
settings:
  tailMode: 50000
  updateInterval: 5
  minSymbolFilter: 3
  disableAutoUpdate: false
  disableMouse: false
  disableTimestamp: false
  onlyStream: false
  dockerContext: default
  kubernetesContext: default
  kubernetesNamespace: all
  customPath: /opt
  colorMode: default
  colorActionsDisable: false
  sinceDateFilterMode: false
  untilDateFilterMode: false
  disableFastMode: false

# Available hotkeys:
# a-z, 0-9, f1-f12 and any other symbols
# tab, shift+tab, enter, space, backspace, del/delete and esc/escape
# shift+<a-z>
# ctrl+<a-z>
hotkeys:
  help: f1
  switchWindow: tab
  backSwitchWindows: shift+tab
  up: k
  quickUp: shift+k
  veryQuickUp: ctrl+k
  switchFilterMode: ctrl+k
  down: j
  quickDown: shift+j
  veryQuickDown: ctrl+j
  backSwitchFilterMode: ctrl+j
  left: h
  right: l
  disableFilterByDate: delete
  loadJournal: enter
  goToFilter: /
  goToEnd: ctrl+e
  goToTop: ctrl+a
  tailModeMore: "]"
  tailModeLess: "["
  updateIntervalMore: "}"
  updateIntervalLess: "{"
  autoUpdateJournal: ctrl+u
  updateJournal: ctrl+r
  updateLists: ctrl+q
  switchColorMode: ctrl+w
  switchPriority: ctrl+p
  switchDockerMode: ctrl+d
  switchStreamMode: ctrl+s
  timestampShow: ctrl+t
  exit: ctrl+c

# Available colors: default, green, black, yellow, red, blue, cyan, magenta, white
interface:
  foregroundColor: default
  backgroundColor: default
  selectedForegroundColor: black
  selectedBackgroundColor: green
  frameColor: default
  titleColor: default
  selectedFrameColor: green
  selectedTitleColor: green
  statusColor: yellow
  errorColor: red