name: Build rpm package and push to Fedora Copr

on:
  workflow_dispatch:

jobs:
  copr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Add rpm format to goreleaser config
        run: echo "      - rpm" >> .goreleaser.yaml

      - name: Build packages using goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          args: release --clean --skip=publish --skip=validate

      - name: Install copr cli
        run: pip install copr-cli

      - name: Publish to Copr
        env:
          COPR_CONFIG: ${{ secrets.COPR_CONFIG }}
        run: |
          mkdir -p ~/.config
          echo "$COPR_CONFIG" > ~/.config/copr
          copr-cli build lazyjournal dist/*.rpm